# Generated by Django 4.2 on 2023-05-17 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(max_length=3000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_data', models.BinaryField(blank=True, editable=True, null=True, verbose_name='Image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('createuser', models.CharField(max_length=100)),
                ('likes', models.ManyToManyField(blank=True, related_name='collected_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
